version: "2"
services:
  nginx:
    image: nginx
    depends_on:
      #otherwise nginx would shutdown immediately because the 'devapp'-host doesn't exist in the docker network
      - devapp
    ports:
      - "9090:443"
    volumes:
      - "/home/core/share/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/home/core/share/nginx/certs:/etc/nginx/certs:ro"

  postgres:
    build: postgres
    ports:
      - "5432:5432"
    volumes:
      - "/home/core/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - DATOMIC_POSTGRES_PASSWORD
  datomicdb:
    build:
      context: transactor
      args:
        LICENSE: ${DATOMIC_LICENSE_KEY}
        DATOMIC_USER: ${DATOMIC_USER}
        DATOMIC_PASSWORD: ${DATOMIC_PASSWORD}
    command: -Ddatomic.sqlPassword=${DATOMIC_POSTGRES_PASSWORD} config/transactor.properties
    ports:
      - "4334:4334"
    volumes:
      - "/home/core/share/transactor/data:/data"
  devapp:
    build:
      context: app
      dockerfile: Dockerfile-uberjar
    command: java -Dclojure.server.repl="{:port 35001 :address \"0.0.0.0\" :accept clojure.core.server/repl}" -jar /usr/src/app/target/app.jar
    ports:
      - "35001:35001"
      - "8000:8000"
    volumes:
      - "/home/core/share/app:/usr/src/app"
      - "/home/core/.m2:/root/.m2"
    environment:
      - DATOMIC_CONNECT_URL=datomic:sql://people?jdbc:postgresql://postgres:5432/datomic?user=datomic&password=${DATOMIC_POSTGRES_PASSWORD}
      - DATOMIC_USER
      - DATOMIC_PASSWORD
      - JIRA_BASE_URL
      - JIRA_TEMPO
      - JIRA_ACCESS_TOKEN
      - JIRA_CONSUMER_PRIVATE_KEY
      - JWS_TOKEN_SECRET
      - APP_HOSTNAME

